gsap.from("#img1",{
    delay:0.5,
    opacity:0, 
    duration:1,
    y:60
});
gsap.from("#img2",{
    delay:0.5,
    opacity:0, 
    duration:1,
    x:60
});
gsap.from("#img3",{
    delay:0.5,
    opacity:0, 
    duration:1,
    y:-60
})
gsap.from("main h1",{
    delay:0.5,
    opacity:0, 
    duration:1
});
gsap.from(".main-p",{
    delay:0.5,
    opacity:0, 
    duration:1
});